export {default as Navbar} from './Navbar'
export {default as Header} from './Header'
export {default as Services} from './Services'
export {default as Methods} from './Methods'
export {default as Pricing} from './Pricing'
export {default as Client} from './Client'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'